### ISSUE TITLE
Build Failiure on windows

### ISSUE THREAD

**Issue by lambwheit** [ifduyue/xxtea#25]
Collecting xxtea
  Using cached xxtea-2.0.0.post0.tar.gz (7.4 kB)
  Preparing metadata (setup.py) ... done
Installing collected packages: xxtea
  DEPRECATION: xxtea is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for xxtea ... error
  error: subprocess-exited-with-error

  × Running setup.py install for xxtea did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running install
      C:\Users\Nuwuy\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building 'xxtea' extension
      creating build
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      "D:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Nuwuy\AppData\Local\Programs\Python\Python311\include -IC:\Users\Nuwuy\AppData\Local\Programs\Python\Python311\Include "-ID:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\include" "-ID:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\ATLMFC\include" "-ID:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /Tcxxtea.c /Fobuild\temp.win-amd64-cpython-311\Release\xxtea.obj
      xxtea.c
      xxtea.c(60): warning C4018: '<': signed/unsigned mismatch
      xxtea.c(194): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      xxtea.c(195): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      xxtea.c(290): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      xxtea.c(291): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      xxtea.c(340): error C2106: '=': left operand must be l-value
      error: command 'D:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> xxtea

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by IlluminatiWave** [comment]
The problem seems to be back in xxtea 3.2.0 (windows 11, python 3.10)

CompileError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 1
distutils.errors.DistutilsExecError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 1

During handling of the above exception, another exception occurred:

distutils.errors.CompileError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 1

During handling of the above exception, another exception occurred:

  File "C:\code\test.py", line 1, in <module>
    import xxtea
cffi.VerificationError: CompileError: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 1

(have VS builds tools 2022)

**Comment by ifduyue** [comment]
@IlluminatiWave Hi, why is there cffi in the log? xxtea didn't use cffi.
